### ISSUE TITLE
strict in index.js causes syntax error when using const

### ISSUE THREAD

**Issue by daviesdoclc** [prantlf/babel-plugin-module-resolver-standalone#1]
The 'use strict' declaration on line 10 causes line 17 to complain on older ES5 browsers.

Unexpected keyword 'const'. Const declarations are not supported in strict mode.

I'm using this in via the requirejs-babel7 plugin so that I can transpile ES6 to ES5 in project using RequireJS.

**Comment by prantlf** [comment]
Yes, you're right. IE will not load the index.js as it is now.

**Comment by prantlf** [comment]
I released the fix as [v0.0.2](https://github.com/prantlf/babel-plugin-module-resolver-standalone/releases/tag/v0.0.2). Thank you for reporting this!
